# Site settings
remote_theme: chesterhow/tale
title: Scrum Owl
description: "スクラムの賢者（スクラムマスター）への道のり"
#baseurl: "/tale"
url: "https://scrumowl.com"
locale: ja_JP
timezone: Asia/Tokyo
future: true

# Google Analytics
#google_analytics: UA—XXXXXXXX-X

# Author
author:
  name: Kosuke Kawasaki
  url: "https://scrumowl.com"
  github: kosukekawasaki
  twitter: KosukeKwsk

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
paginate: 5
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:title
      excerpt_separator: <!--more-->

# Excludes
exclude: [ Gemfile, Gemfile.lock ]
